### PR TITLE
Updated for iFrames

### PR DESCRIPTION
**Pull request by jsmylnycky**
Removed all scaffolding directives since its now part of the appRunner project.
Removed bootstrap service.
Removed the 'run' functionality for redirecting away from the intro page.  Handled by AppRunner.
Removed alerts, now in AppRunner.
Updated HeaderOptions links for iframe support.
Made select options optional to avoid errors on unsupplied params.
Adjusted user/account prefs lookup to ignore getting app info if requested app scope is core.
Added events for app change and page change.
Disabled session caches for now.

### CODE REVIEW

**Comment by mbebas** [comment]
:+1:

**Comment by darushka** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by jsmylnycky** [comment]
v1.0.0

**Pull request closed without merging**
