### PR TITLE
Fix for 1247

### PR DESCRIPTION
**Pull request by rwrzesien**

### CODE REVIEW

**Comment by jsmylnycky** [comment]
@rwrzesien  Make sure you update and add unit tests as needed.

**Comment by rwrzesien** [comment]
@jsmylnycky Updated.

**Comment by jsmylnycky** [comment]
:+1:

**Comment by mbebas** [comment]
:+1:

**Comment by jsmylnycky** [comment]
please merge squash

**Comment by rwrzesien** [comment]
@jsmylnycky Merged and pushed, commit:
1ad2434ed163de64ce9667e9c7debbffbc3c05ed

**Comment by jsmylnycky** [comment]
v1.0.7

**Pull request closed without merging**
