### PR TITLE
2754 select all when too few items 2

### PR DESCRIPTION
**Pull request by legendary-mich**
https://peachworks.leankit.com/Boards/View/267929177/367379820

On the peach-select controll when there were too few items (2 or less), toggling an item did not select/unselect the All checkbox.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
👍

**Comment by PSkierniewski** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@legendary-mich please merge/squash

**Comment by legendary-mich** [comment]
@jsmylnycky merged

**Comment by jsmylnycky** [comment]
v2.0.13

**Pull request closed without merging**
