### PR TITLE
Fix for CUST-2232 Select location pop does not go away

### PR DESCRIPTION
**Pull request by rwrzesien**
This should fix:
https://whentomanage.atlassian.net/browse/CUST-2232

### CODE REVIEW

**Comment by jsmylnycky** [comment]
@rwrzesien  I'd like to see a unit test that stubs out the modal cancel function to confirm its been called please

**Comment by rwrzesien** [comment]
@jsmylnycky Updated.

**Comment by jsmylnycky** [comment]
:+1:  You can merge squash this

**Comment by rwrzesien** [comment]
@jsmylnycky Merged and pushed, commit:
739ab73cfac7fadf8ec8def17f5bb85d0cf68928

**Comment by jsmylnycky** [comment]
Deployment succeeded for Peach-Web2 on deployment id d-8G10KKD8C

Deployment data: 
{
    "commit_id": "da59a5aa9f45dbfa575e4e548b5ebcaf3238e838", 
    "environment": "production", 
    "description": "v0.5.0", 
    "success": true, 
    "deploy_id": "d-8G10KKD8C", 
    "error_message": null, 
    "user_name": "jsmylnycky", 
    "app": "Peach-Web2", 
    "deploy_data": {
        "Failed": 0, 
        "InProgress": 0, 
        "Skipped": 0, 
        "Succeeded": 2, 
        "Pending": 0
    }
}

**Pull request closed without merging**
