### PR TITLE
Cust 1784 dashboard account prefs

### PR DESCRIPTION
**Pull request by jsmylnycky**

### CODE REVIEW

**Comment by darushka** [comment]
:+1: 
@jsmylnycky 
Those new rules for displaying dashboard make me apply these updates to my branch https://github.com/peachworks/ngPeach/tree/CUST-1841_show_Help_App_to_permissioned_users, where I move the defining of dashboard accessibility for user to $peachAccess service.

**Comment by jsmylnycky** [comment]
Thanks @darushka , figured there would be some overlap there :)

I expect your PRs to go out first, so I'll have to update this to reflect the new $peachAccess tool.

**Comment by darushka** [comment]
@jsmylnycky 
Sounds good to me.

:+1:

**Comment by rwrzesien** [comment]
:+1:

**Comment by againsley** [comment]
:+1:

**Comment by DarrylD** [comment]
:+1:

**Comment by rynomars** [comment]
:thumbsup:

**Comment by jsmylnycky** [comment]
Released v0.4.4

**Pull request closed without merging**
