### PR TITLE
Hide Dashboard if not subscribed to POS

### PR DESCRIPTION
**Pull request by jsmylnycky**
Added in work arounds to not display the dashboard app unless conditions are met and POS is an available app

This is temporary until /widgets returns empty sets instead of 401

### CODE REVIEW

**Comment by darushka** [comment]
@jsmylnycky 

I guess it would be better instead of updating sidebar, toolbar and apps-menu, add the check if pos is among avaialble apps just to $peachAccess service, then we don't need any additional checks.

**Comment by jsmylnycky** [comment]
@darushka I thought about it but i didnt want to muck up $peachAccess with having to pull all of the users apps as well.

I flipped a coin since neither my solution or the $peachAccess solution are pretty :)  It should only be this way for a week or so.

**Comment by darushka** [comment]
:+1: while its a temp solution

**Comment by jsmylnycky** [comment]
Deployment succeeded for Peach-Web2-profile-app on deployment id d-BME5S6ZEB

Deployment data: 
{
    "commit_id": "96ac9bf9d468710e64e6efaa1c8324da774d7387", 
    "environment": "production", 
    "description": "v0.2.1", 
    "success": true, 
    "deploy_id": "d-BME5S6ZEB", 
    "error_message": null, 
    "user_name": "jsmylnycky", 
    "app": "Peach-Web2-profile-app", 
    "deploy_data": {
        "Failed": 0, 
        "InProgress": 0, 
        "Skipped": 0, 
        "Succeeded": 2, 
        "Pending": 0
    }
}

**Comment by jsmylnycky** [comment]
Released v0.5.6

**Pull request closed without merging**
