### PR TITLE
Adding onOpen, onClose methods to the Peach Card directive

### PR DESCRIPTION
**Pull request by rynomars**
Adding onOpen, onClose methods to the Peach Card directive.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
👍  in the future, dont bump the package versions please.  I'll take care of that in the master branch prior to release so I can ensure its the proper version then.  Otherwise I'm going to naturally bump it and it'll be 2 versions over the current one.

**Comment by rynomars** [comment]
@jsmylnycky gotcha! That makes sense.

**Comment by rynomars** [comment]
@jsmylnycky I put the version back to 2.0.11 in package.json and bower.json

**Comment by rynomars** [comment]
@jsmylnycky I had QA test this change in an inventory build. I received the thumbs.

**Comment by darushka** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@rynomars please merge squash

**Comment by jsmylnycky** [comment]
v2.0.12

**Pull request closed without merging**
