### PR TITLE
Cust 2091 i pad button not working

### PR DESCRIPTION
**Pull request by darushka**
This PR solves major issue with buttons in Page Header components which didn't redirect the user to the selected page on iPad.

There were ng-click and ng-href attributes on each button. I have removed ng-href and put redirect to selected page into controller.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by darushka** [comment]
@jsmylnycky 
Should I merge this?

**Comment by jsmylnycky** [comment]
@darushka go ahead

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeach/commit/edf881f6bb45706e7f24a2a32f50f851734ee73d

**Comment by jsmylnycky** [comment]
Released v0.5.7

**Pull request closed without merging**
