### PR TITLE
Cust 1256 add alerts modal

### PR DESCRIPTION
**Pull request by darushka**
This PR si for story https://whentomanage.atlassian.net/browse/CUST-1270.

It adds Alerts link to User Menu if user is permissioned to alerts and creates a full page modal for Alerts where user can manage his alerts.

Note: there is not 100% coverage on AlertsController, because we need to ignore moment.js from unit tests. Now .jshintrc seems to be not working as expected.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeach/commit/3fa41f99f9e41cfe59aeabd5965b1555a412b2fd

**Comment by jsmylnycky** [comment]
Releasing with v0.5.8

**Comment by jsmylnycky** [comment]
ngPeach 0.5.8

**Pull request closed without merging**
