### PR TITLE
float all apps icon to the left

### PR DESCRIPTION
**Pull request by darushka**
This PR makes All Apps icon positioned right after apps with a free space between it and Config icon.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
@darushka  Just to confirm, if you shrink the screen down, icons end up in the All Apps menu properly, correct?  The math can be a bit touchy.

**Comment by jsmylnycky** [comment]
:+1:

**Comment by darushka** [comment]
The icons end up in the All Apps menu properly.

**Comment by jsmylnycky** [comment]
Please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeach/commit/9fbf9322f5b3509a98e149833651fcfd8619fbd8

**Comment by jsmylnycky** [comment]
Released v0.3.42

**Pull request closed without merging**
