### PR TITLE
Cust 1192 mobile sidenav

### PR DESCRIPTION
**Pull request by jsmylnycky**
Accordion Component: Utilizes panels, header and body directives to build out toggle functionality
Toolbar: In mobile, it will show the app icon as well as the title centered on the screen
User Menu: Shows the Help and Config options when it mobile mode
Sidenav: Shows apps utilizing the accordion in mobile mode, expandable to show the pages for each app.  Dashboard and Reports are displayed at the top and bottom, respectively, and are just links instead of accordion panels.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
@darushka  This one is pretty massive, sorry! Please review at your earliest convenience so I can try to get it merged into master today.

**Comment by darushka** [comment]
@jsmylnycky  It is very cool, but I see a parallel with peach-page-header directive. Shouldn't it be the case that we may want to use more simple solution, based on angular material components, instead of our own complicated structure?

**Comment by jsmylnycky** [comment]
@darushka  In regards to which part, the accordion?

Material doesn't have an accordion.  We do need to enforce the use of things such as panels for each header/body pairing.  While we could leave it up to the developer to put in their own markup for the header and body, I feel like that is leaving the developer open to a lot of incorrect implementations.

Do you have any suggestions in mind on how we could change it?  Open to hearing anything.

**Comment by darushka** [comment]
:+1:

**Comment by jsmylnycky** [comment]
Released v0.2.63

**Pull request closed without merging**
