### PR TITLE
Updated hidden intro page check to make sure value is set to true

### PR DESCRIPTION
**Pull request by jsmylnycky**

### CODE REVIEW

**Comment by rynomars** [comment]
:+1:

**Comment by darushka** [comment]
:+1:

**Comment by rwrzesien** [comment]
:+1:

**Comment by jsmylnycky** [comment]
v0.7.5

**Comment by jsmylnycky** [comment]
Deployment succeeded for Peach-Web2 on deployment id d-11FZV17HC

Deployment data: 
{
    "commit_id": "823fa7a5e619679f66e6f472498ef8e185a26a13", 
    "environment": "production", 
    "description": "v0.5.3", 
    "success": true, 
    "deploy_id": "d-11FZV17HC", 
    "error_message": null, 
    "user_name": "jsmylnycky", 
    "app": "Peach-Web2", 
    "deploy_data": {
        "Failed": 0, 
        "InProgress": 0, 
        "Skipped": 0, 
        "Succeeded": 2, 
        "Pending": 0
    }
}

**Pull request closed without merging**
