### PR TITLE
Added exception for reset password 401 response

### PR DESCRIPTION
**Pull request by rwrzesien**
This is necessary for https://whentomanage.atlassian.net/browse/CUST-1927 to work.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by rwrzesien** [comment]
@jsmylnycky Added unit test.

**Comment by rynomars** [comment]
:thumbsup:

**Comment by jsmylnycky** [comment]
:+1: @rwrzesien  please merge squash

**Comment by rwrzesien** [comment]
@jsmylnycky Merged and pushed, commit:
4fd7c253aa90b15fee4b3549e7f85195b27f7c07

**Comment by jsmylnycky** [comment]
Released v0.6.3

**Pull request closed without merging**
