### PR TITLE
Fix Alert modal to fit the page

### PR DESCRIPTION
**Pull request by darushka**
This PR solves the issue https://whentomanage.atlassian.net/browse/CUST-2141

### CODE REVIEW

**Comment by jsmylnycky** [comment]
@darushka  Is it necessary to even set a variable within the controller?  In the ngPeach run block, we're setting it on the $rootScope, which means you should only have to do:

```
ng-class="{'full-width': !states.showSidenav}"
```

**Comment by darushka** [comment]
@jsmylnycky 
I tried to use it, as you said, but it doesn't work

**Comment by rwrzesien** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@darushka please merge squash

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeach/commit/a35412376f9e14fb510881a1b0f999831e93ee83

**Comment by jsmylnycky** [comment]
v0.7.7

**Pull request closed without merging**
