### PR TITLE
Fix for CUST-296 do not show location selector if account has only 1 location

### PR DESCRIPTION
**Pull request by rwrzesien**

### CODE REVIEW

**Comment by rynomars** [comment]
:+1:

**Comment by darushka** [comment]
:+1:

**Comment by mbebas** [comment]
:+1:

**Comment by jsmylnycky** [comment]
@rwrzesien  please merge squash

**Comment by rwrzesien** [comment]
@jsmylnycky Merged and pushed, commit:
196fae3b33540d91d60e273935601dad25f0d955

**Comment by jsmylnycky** [comment]
v0.7.17

**Pull request closed without merging**
