### PR TITLE
CUST 1736 Fixed up the paths for sidenav links in mobile

### PR DESCRIPTION
**Pull request by jsmylnycky**
Also removed a couple filters for optimization

### CODE REVIEW

**Comment by darushka** [comment]
:+1:

**Comment by darushka** [comment]
@jsmylnycky 
Did those filters sagnificantly influence mobile performance?

**Comment by jsmylnycky** [comment]
@darushka  I don't have any metrics to say how they may have influenced performance, but it's a best practice to avoid filters in the template because it forces the the digest to have to happen twice for it to work.  It's faster to do it on the object directly.

**Comment by jsmylnycky** [comment]
Released v0.3.32

**Pull request closed without merging**
