### PR TITLE
2772 - peach select

### PR DESCRIPTION
**Pull request by legendary-mich**
https://peachworks.leankit.com/Boards/View/267929177/364160874
peach-select did not select all values when options were passed after initialization

### CODE REVIEW

**Comment by mbebas** [comment]
:+1:

**Comment by PSkierniewski** [comment]
:+1:

**Comment by legendary-mich** [comment]
@jsmylnycky After the previous bugfix, peach-select didn't work correctly with the search object provided, so I excluded it as the seach-object was never a part of the problem. Now everything seems to work fine, but there still may be issues that I'm not aware of.

**Comment by jsmylnycky** [comment]
v2.0.14

**Pull request closed without merging**
