### PR TITLE
Fixed issue with update of user alert events

### PR DESCRIPTION
**Pull request by darushka**
This PR resolves bug https://whentomanage.atlassian.net/browse/CUST-2179.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1: 

Bonus points for fixing Aria Labels.  Thanks!

**Comment by jsmylnycky** [comment]
@darushka Go ahead and merge this in the morning, its small enough that a second review isnt necessary

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeach/commit/dcf9fa72808de14e765bd2bb8333cf9ff1692f12

**Comment by jsmylnycky** [comment]
Released ngPeach v0.6.2

**Pull request closed without merging**
