### PR TITLE
Added default user profile image for global nav

### PR DESCRIPTION
**Pull request by darushka**
CARD-681 Prod - Global Nav - Missing default thumb nail image
https://peachworks.leankit.com/Boards/View/267929177/287230625

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by jsmylnycky** [comment]
Please merge squash

**Comment by rynomars** [comment]
:+1:

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeach/commit/64dec7724e9004e2d94c6fde06aef16d4b4dd620

**Comment by jsmylnycky** [comment]
v0.8.4

**Pull request closed without merging**
