### PR TITLE
add ability to hide header options on mobile depending on their length

### PR DESCRIPTION
**Pull request by darushka**
A small  fix which allows to display condensed nav in card header on mobile screen only when there are header options. It allows us to manipulate hiding/showing header options by cleaning them or adding in a controller.

### CODE REVIEW

**Comment by jsmylnycky** [comment]
:+1:

**Comment by mbebas** [comment]
:+1:

**Comment by rynomars** [comment]
:+1:

**Comment by darushka** [comment]
Merged squash https://github.com/peachworks/ngPeach/commit/6ffdfe9c8fdfdbe8ac80fa35757ac4e28fa1ea29

**Comment by jsmylnycky** [comment]
v1.0.2

**Pull request closed without merging**
