### PR TITLE
Swapped out all calls for peachjs

### PR DESCRIPTION
**Pull request by jsmylnycky**
https://github.com/peachworks/peachjs

See the above repo for the ES6 implementation of peachjs that does NOT have any ties to angular at all.

### CODE REVIEW

**Comment by rynomars** [comment]
besides failing tests, looks good. nice and clean! :+1:

**Comment by mbebas** [comment]
:+1:

**Comment by jsmylnycky** [comment]
Merging now that all unit tests are back to 100% coverage and passing.

**Comment by jsmylnycky** [comment]
v2.0.1

**Pull request closed without merging**
